LOAD DATA INFILE '/tmp/jery/tables/Financial.txt'
TRUNCATE
INTO TABLE FINANCIAL 
FIELDS TERMINATED BY '|'
(  FI_CO_ID ,          
 FI_YEAR ,
 FI_QTR ,
 FI_QTR_START_DATE DATE "YYYY-MM-DD" ,
 FI_REVENUE ,
 FI_NET_EARN ,
 FI_BASIC_EPS ,
 FI_DILUT_EPS ,
 FI_MARGIN ,
 FI_INVENTORY ,
 FI_ASSETS ,
 FI_LIABILITY ,
 FI_OUT_BASIC ,
 FI_OUT_DILUT        
)
