LOAD DATA INFILE '/tmp/jery/tables/NewsItem.txt'
TRUNCATE
INTO TABLE NEWS_ITEM 
FIELDS TERMINATED BY '|'
(  NI_ID ,          
 NI_HEADLINE ,
 NI_SUMMARY ,
 NI_ITEM CHAR(100000) ,
 NI_DTS TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF9" ,
 NI_SOURCE ,
 NI_AUTHOR        
)
