LOAD DATA INFILE '/tmp/jery/tables/Settlement.txt'
TRUNCATE
INTO TABLE SETTLEMENT 
FIELDS TERMINATED BY '|'
(  SE_T_ID ,          
 SE_CASH_TYPE ,
 SE_CASH_DUE_DATE DATE "YYYY-MM-DD" ,
 SE_AMT        
)
